name: Apply Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: Deployment environment (dev|stg|prod)
        required: true
        type: string

jobs:
  shared:
    runs-on: ubuntu-latest
    concurrency: infra-shared-${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: FIAP-POS-TECH-13SOAT-MECHANICS/mechanics-infra
          path: infra-repo
          ref: ${{ github.ref }}
          token: ${{ secrets.INFRA_PAT }}
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: FIAP-POS-TECH-13SOAT-MECHANICS/mechanics-infra/.github/actions/apply-terraform-module@main
        with:
          environment: ${{ inputs.environment }}
          module_name: shared
          module_path: infra-repo/shared
