name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release
      - develop

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  resolve-environment:
    name: Resolve environment name
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.resolve.outputs.environment }}
    steps:
      - uses: actions/checkout@v5
      - name: Resolve Environment
        id: resolve
        uses: FIAP-POS-TECH-13SOAT-MECHANICS/mechanics-infra/.github/actions/resolve-environment@main

  discover:
    name: Discover services
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.list.outputs.services }}
    steps:
      - uses: actions/checkout@v5
      - name: List services
        id: list
        uses: ./.github/actions/discover-services

  validate:
    name: Validate infrastructure
    needs:
      - discover
    uses: ./.github/workflows/validate.yml
    with:
      services: ${{ needs.discover.outputs.services }}
    secrets: inherit

  shared:
    name: Apply shared infrastructure
    needs:
      - resolve-environment
      - validate
    uses: ./.github/workflows/apply-shared.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
    secrets: inherit

  apply-databases:
    name: Apply databases infrastructure
    needs:
      - resolve-environment
      - shared
      - discover
    uses: ./.github/workflows/apply-dbs.yml
    with:
      environment: ${{ needs.resolve-environment.outputs.environment }}
      services: ${{ needs.discover.outputs.services }}
    secrets: inherit
